version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - salam_network

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Configuration de la base de données (à adapter)
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employeesdb
      SPRING_DATASOURCE_USERNAME: olsen
      SPRING_DATASOURCE_PASSWORD: "oZt(1z48bw[plR)G"
    depends_on:
      - db
    restart: always
    networks:
      - salam_network


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "oZt(1z48bw[plR)G"
      MYSQL_DATABASE: employeesdb
      MYSQL_USER: olsen
      MYSQL_PASSWORD: "oZt(1z48bw[plR)G"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

    networks:
      - salam_network

volumes:
  db_data:
networks:
  salam_network:
    name: salam_network

