version: "3.8"

services:
  frontend:
    image: m1ra/projet_devops_gestionemploye-frontend:1.1
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always
    networks:
      - salam_network

  backend:
    image: m1ra/projet_devops_gestionemploye-backend:1.1
    build: ./BACKEND
    ports:
      - "8081:8081"
    environment:
      # Configuration de la base de données (à adapter)
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employeesdb
      SPRING_DATASOURCE_USERNAME: olsen
      SPRING_DATASOURCE_PASSWORD: "oZt(1z48bw[plR)G" # Mot de passe directement dans le fichier
    depends_on:
      - db
    restart: always
    networks:
      - salam_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "oZt(1z48bw[plR)G"  # Mot de passe root directement dans le fichier
      MYSQL_DATABASE: employeesdb
      MYSQL_USER: olsen
      MYSQL_PASSWORD: "oZt(1z48bw[plR)G"  # Mot de passe directement dans le fichier
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - salam_network

volumes:
  db_data:
networks:
  salam_network:
    name: salam_network